apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app.kubernetes.io/name: wdl
    app.kubernetes.io/component: gateway
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app.kubernetes.io/name: wdl
    app.kubernetes.io/component: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app.kubernetes.io/name: wdl
    app.kubernetes.io/component: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wdl
      app.kubernetes.io/component: gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wdl
        app.kubernetes.io/component: gateway
    spec:
      containers:
        - name: gateway
          image: docker.io/getwdl/wdl-workerd:latest
          command: ["workerd"]
          args:
            - serve
            - -b
            - /app/dist/workerd-configs/gateway.bin
          envFrom:
            - configMapRef:
                name: wdl-config
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 1Gi
