x-rust-published: &rust-published
  image: docker.io/getwdl/wdl-rust:latest
  pull_policy: always
  build: !reset null

x-workerd-published: &workerd-published
  image: docker.io/getwdl/wdl-workerd:latest
  pull_policy: always
  build: !reset null

services:
  redis-proxy-user:
    <<: *rust-published
  redis-proxy-system:
    <<: *rust-published
  redis-proxy-do:
    <<: *rust-published
  scheduler:
    <<: *rust-published
  workflows:
    <<: *rust-published
  user-runtime:
    <<: *workerd-published
  system-runtime:
    <<: *workerd-published
  gateway:
    <<: *workerd-published
  d1-runtime:
    <<: *workerd-published
  d1-runtime-a:
    <<: *workerd-published
  d1-runtime-b:
    <<: *workerd-published
  d1-runtime-c:
    <<: *workerd-published
  do-runtime:
    <<: *workerd-published
  do-runtime-a:
    <<: *workerd-published
  do-runtime-b:
    <<: *workerd-published
  do-runtime-c:
    <<: *workerd-published
