using Workerd = import "/workerd/workerd.capnp";

const config :Workerd.Config = (
  services = [
    (name = "d1-runtime", worker = .d1RuntimeWorker),
    # Durable Object SQL state must use persistent localDisk storage. Do not
    # switch this to memory: D1 database files live under this disk service.
    (name = "d1-storage", disk = (path = "/data/d1", writable = true)),
    (name = "network", network = (
      allow = ["private", "public"],
      tlsOptions = (trustBrowserCas = true),
    )),
  ],

  sockets = [
    (name = "http", address = "*:8787", http = (), service = "d1-runtime"),
  ],
);

const d1RuntimeWorker :Workerd.Worker = (
  modules = [
    (name = "worker", esModule = embed "index.js"),
    (name = "d1-runtime-actor", esModule = embed "actor.js"),
    (name = "d1-runtime-http", esModule = embed "http.js"),
    (name = "d1-runtime-ops", esModule = embed "ops.js"),
    (name = "d1-runtime-owner-client", esModule = embed "owner-client.js"),
    (name = "d1-runtime-owner-registry", esModule = embed "owner-registry.js"),
    (name = "d1-runtime-protocol", esModule = embed "protocol.js"),
    (name = "d1-runtime-read-cache", esModule = embed "read-cache.js"),
    (name = "d1-runtime-router", esModule = embed "router.js"),
    (name = "d1-runtime-state", esModule = embed "state.js"),
    (name = "d1-runtime-test-hooks", esModule = embed "test-hooks.js"),
    (name = "d1-runtime-task-identity", esModule = embed "task-identity.js"),
    (name = "shared-redis", esModule = embed "../shared/redis.js"),
    (name = "shared-redis-command-client", esModule = embed "../shared/redis-command-client.js"),
    (name = "shared-redis-resp", esModule = embed "../shared/redis-resp.js"),
    (name = "shared-redis-session", esModule = embed "../shared/redis-session.js"),
    (name = "shared-redis-subscriber", esModule = embed "../shared/redis-subscriber.js"),
    (name = "hex.js", esModule = embed "../shared/hex.js"),
    (name = "errors.js", esModule = embed "../shared/errors.js"),
    (name = "shared-errors", esModule = embed "../shared/errors.js"),
    (name = "shared-observability", esModule = embed "../shared/observability.js"),
    (name = "shared-respond", esModule = embed "../shared/respond.js"),
    (name = "shared-request-scope", esModule = embed "../shared/request-scope.js"),
    (name = "shared-env", esModule = embed "../shared/env.js"),
    (name = "shared-fnv1a32", esModule = embed "../shared/fnv1a32.js"),
    (name = "shared-ns-pattern", esModule = embed "../shared/ns-pattern.js"),
    (name = "shared-task-identity", esModule = embed "../shared/task-identity.js"),
    (name = "shared-owner-endpoint", esModule = embed "../shared/owner-endpoint.js"),
    (name = "shared-owner-lease", esModule = embed "../shared/owner-lease.js"),
    (name = "shared-optimistic-retry", esModule = embed "../shared/optimistic-retry.js"),
    (name = "shared-owner-protocol", esModule = embed "../shared/owner-protocol.js"),
    (name = "shared-owner-forwarder", esModule = embed "../shared/owner-forwarder.js"),
    (name = "shared-redis-client", esModule = embed "../shared/redis-client.js"),
    (name = "shared-d1-data-field", esModule = embed "../shared/d1-data-field.js"),
    (name = "shared-d1-params", esModule = embed "../shared/d1-params.js"),
    (name = "shared-bounded-body", esModule = embed "../shared/bounded-body.js"),
    (name = "shared-d1-transport", esModule = embed "../shared/d1-transport.js"),
    (name = "shared-d1-query-wire", esModule = embed "../shared/d1-query-wire.js"),
    (name = "shared-d1-timeout", esModule = embed "../shared/d1-timeout.js"),
    (name = "shared-internal-auth", esModule = embed "../shared/internal-auth.js"),
  ],
  compatibilityDate = "2026-04-24",
  globalOutbound = "network",
  durableObjectNamespaces = [
    (className = "D1DatabaseActor", uniqueKey = "wdl-d1-storage-v1", enableSql = true),
  ],
  durableObjectStorage = (localDisk = "d1-storage"),
  bindings = [
    (name = "D1_DATABASES", durableObjectNamespace = "D1DatabaseActor"),
    (name = "REDIS_ADDR", fromEnvironment = "REDIS_ADDR"),
    (name = "WDL_INTERNAL_AUTH_TOKEN", fromEnvironment = "WDL_INTERNAL_AUTH_TOKEN"),
    (name = "WDL_INTERNAL_AUTH_PREVIOUS_TOKEN", fromEnvironment = "WDL_INTERNAL_AUTH_PREVIOUS_TOKEN"),
    (name = "D1_TASK_ID", fromEnvironment = "D1_TASK_ID"),
    (name = "D1_TASK_ENDPOINT", fromEnvironment = "D1_TASK_ENDPOINT"),
    (name = "D1_TASK_CONTAINER_NAME", fromEnvironment = "D1_TASK_CONTAINER_NAME"),
    (name = "D1_TASK_IDENTITY_TIMEOUT_MS", fromEnvironment = "D1_TASK_IDENTITY_TIMEOUT_MS"),
    (name = "ECS_CONTAINER_METADATA_URI_V4", fromEnvironment = "ECS_CONTAINER_METADATA_URI_V4"),
    (name = "D1_OWNER_TTL_SECONDS", fromEnvironment = "D1_OWNER_TTL_SECONDS"),
    (name = "D1_OWNER_LEASE_GUARD_MS", fromEnvironment = "D1_OWNER_LEASE_GUARD_MS"),
    (name = "D1_PROBE_TIMEOUT_MS", fromEnvironment = "D1_PROBE_TIMEOUT_MS"),
    (name = "D1_QUERY_TIMEOUT_MS", fromEnvironment = "D1_QUERY_TIMEOUT_MS"),
    (name = "D1_MAX_RESULT_ROWS", fromEnvironment = "D1_MAX_RESULT_ROWS"),
    (name = "D1_MAX_RESULT_BYTES", fromEnvironment = "D1_MAX_RESULT_BYTES"),
    (name = "D1_ACTOR_IDLE_WAIT_TIMEOUT_MS", fromEnvironment = "D1_ACTOR_IDLE_WAIT_TIMEOUT_MS"),
    (name = "D1_DRAIN_TIMEOUT_MS", fromEnvironment = "D1_DRAIN_TIMEOUT_MS"),
    (name = "D1_RENEW_CONCURRENCY", fromEnvironment = "D1_RENEW_CONCURRENCY"),
    (name = "D1_DRAIN_CONCURRENCY", fromEnvironment = "D1_DRAIN_CONCURRENCY"),
    (name = "D1_OBSERVED_OWNER_TTL_MS", fromEnvironment = "D1_OBSERVED_OWNER_TTL_MS"),
    (name = "D1_OBSERVED_OWNER_MAX_ENTRIES", fromEnvironment = "D1_OBSERVED_OWNER_MAX_ENTRIES"),
    (name = "D1_READ_CACHE_TTL_MS", fromEnvironment = "D1_READ_CACHE_TTL_MS"),
    (name = "D1_READ_CACHE_MAX_ENTRIES", fromEnvironment = "D1_READ_CACHE_MAX_ENTRIES"),
    (name = "D1_TEST_HOOKS", fromEnvironment = "D1_TEST_HOOKS"),
    (name = "LOG_LEVEL", fromEnvironment = "LOG_LEVEL"),
  ],
);
